// src/components/Header.tsx
import React from 'react';
import styled from 'styled-components';

const HeaderContainer = styled.header`
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 20px;
  background-color: ${({ theme }) => theme.headerBackground};
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
`;

const Title = styled.h1`
  font-size: 24px;
  color: ${({ theme }) => theme.text};
`;

const ThemeButton = styled.button`
  background-color: ${({ theme }) => theme.buttonBackground};
  color: ${({ theme }) => theme.buttonText};
  border: none;
  padding: 10px 20px;
  border-radius: 5px;
  font-size: 16px;
  cursor: pointer;
  transition: background-color 0.3s;

  &:hover {
    background-color: ${({ theme }) => theme.buttonHover};
  }
`;

interface HeaderProps {
  toggleTheme: () => void;
  isDarkMode: boolean;
}

const Header: React.FC<HeaderProps> = ({ toggleTheme, isDarkMode }) => {
  return (
    <HeaderContainer>
      <Title>Rick and Morty App</Title>
      <ThemeButton onClick={toggleTheme}>
        {isDarkMode ? 'Modo Claro' : 'Modo Escuro'}
      </ThemeButton>
    </HeaderContainer>
  );
};

export default Header;

// src/components/Header.vue
<template>
  <HeaderContainer>
    <Title>Rick and Morty App</Title>
    <ThemeButton @click="toggleTheme">
      {{ isDarkMode ? 'Modo Claro' : 'Modo Escuro' }}
    </ThemeButton>
  </HeaderContainer>
</template>

<script setup>
import styled from 'vue-styled-components';
import { defineProps } from 'vue';

const props = defineProps({
  toggleTheme: Function,
  isDarkMode: Boolean,
});

const HeaderContainer = styled.header`
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 20px;
  background-color: ${(props) => props.theme.headerBackground};
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
`;

const Title = styled.h1`
  font-size: 24px;
  color: ${(props) => props.theme.text};
`;

const ThemeButton = styled.button`
  background-color: ${(props) => props.theme.buttonBackground};
  color: ${(props) => props.theme.buttonText};
  border: none;
  padding: 10px 20px;
  border-radius: 5px;
  font-size: 16px;
  cursor: pointer;
  transition: background-color 0.3s;

  &:hover {
    background-color: ${(props) => props.theme.buttonHover};
  }
`;
</script>
